version: '3.4'

services:
  apigateway:
    image: apigateway
    build:
      context: .
      dockerfile: Src/Dockerfile
    networks:
      - traefik
      - gateway
    labels:
      - traefik.enable=true
      - traefik.docker.network=traefik
      - traefik.http.routers.apigateway.entryPoints=websecure
      - traefik.http.routers.apigateway.tls=true
      - traefik.http.routers.apigateway.service=apigateway
      - traefik.http.routers.apigateway.rule=Host("api.netboot.fr")
      - traefik.http.routers.apigateway.tls.certresolver=letsencrypt
      - traefik.http.services.apigateway.loadbalancer.server.port=443
      - traefik.http.services.apigateway.loadbalancer.server.scheme=https

networks:
  gateway:
    external: true
  traefik:
    external: true