name: Update API Gateway

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 0 * * SUN'

jobs:
  build:
    # Define the execution on the self-hosted server.
    runs-on: [self-hosted]
          
    # Define all the steps of the workflow
    steps:
      # Checking out the repository
      - name: Checking out the repository
        uses: actions/checkout@v2

      # Update associated images
      - name: Update associated images
        run: "sudo /usr/local/bin/docker-compose -p gateway pull"
        
      # Stop Containers
      - name: Stop Containers
        run: "sudo /usr/local/bin/docker-compose -p gateway stop"
        
      # Start Containers
      - name: Start Containers
        run: "sudo /usr/local/bin/docker-compose -p gateway up -d"